### ISSUE TITLE
Miss AsyncTCP.h

### ISSUE THREAD

**Issue by sibylpaolatirro** [Pius171/esp8266-wifi-extender#1]
Hello
I tried to compile the sketch but it can't find the AsyncTCP.h library
I have tried a few, but I keep getting errors.
Which one should be used in the project?

Thank you
![image](https://user-images.githubusercontent.com/20536022/203835341-f07252d6-b825-4493-986e-93d8589229a6.png)

**Comment by Pius171** [comment]
![image](https://user-images.githubusercontent.com/70412012/203852935-32e9b9dd-c951-4b42-9050-72f581cab682.png)
AsyncTCP is not used in the code, I used ESP AsynTCP. I have uploaded the library files, so you can download them now.

**Comment by Pius171** [comment]
You can just flash your esp with the binary file provided to save yourself any further stress @sibylpaolatirro
