### ISSUE TITLE
connecting 2 or more in a chain

### ISSUE THREAD

**Issue by PetRatty** [Pius171/esp8266-wifi-extender#2]
I tried connecting a 2nd device to the 1st in a chain like fashion, because of the non auto mesh workaround you mentioned, but my mobile devices report no internet connection. the led status flashing says they are connected but just no internet.
I don't think it is your code as it works with 1 as expected, just connecting the 2nd to the 1st doesn't work (the connection works, not internet traffic). Wondering what is going on under hood

**Comment by Pius171** [comment]
Hi, sorry for the late reply, I am just seeing this. The last time I tried it worked, but I will rerun another test to see if I will get the same issue. You can look up the code if you are interested in what is going on under the hood.
