### ISSUE TITLE
Cannot find ESPAsyncWebServer.h

### ISSUE THREAD

**Issue by Florian-Mahlberg** [Pius171/esp8266-wifi-extender#4]
Hey,
I am trying to fork this project myself to make some changes for my personal use, but I can't find "ESPAsyncWebServer.h"... 
Is there some other Libary I need?

My Error if you care:
`fatal error: ESPAsyncWebServer.h: No such file or directory
    7 | #include <ESPAsyncWebServer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1`

**Comment by svdrummer** [comment]
Google espasyncwebserver.h
It is saying, you don't have that library installed.

**Comment by Pius171** [comment]
the zip file is in the repository, just add it to your Arduino library. You can google search how to add a zip library to Arduino. To save yourself the trouble you can just flash the esp8266 with the binary file in [esp8266-wifi-extender/wifi_extender/](https://github.com/Pius171/esp8266-wifi-extender)/wifi_extender/
